version: '3'

services:
  mesos-master:
    image: mesosphere/mesos-master:1.7.0
    hostname: mesos-master
    entrypoint: [ "mesos-master" ]
    ports:
      - "5050:5050"
    depends_on:
      - zookeeper
    environment:
      - MESOS_CLUSTER=local
      - MESOS_HOSTNAME=mesos-master.docker
      - MESOS_LOG_DIR=/var/log
      - MESOS_WORK_DIR=/var/lib/mesos
      - MESOS_QUORUM=1
      - MESOS_ZK=zk://zookeeper:2181/mesos

  mesos-slave:
    image: mesosphere/mesos-slave:1.7.0
    entrypoint:
      - mesos-slave
    privileged: true
    hostname: mesos-slave
    ports:
      - "5051:5051"
    depends_on:
      - zookeeper
      - mesos-master
    environment:
      - MESOS_CONTAINERIZERS=docker,mesos
      - MESOS_ISOLATOR=cgroups/cpu,cgroups/mem
      - MESOS_LOG_DIR=/var/log
      - MESOS_MASTER=zk://zookeeper:2181/mesos
      - MESOS_PORT=5051
      - MESOS_WORK_DIR=/var/lib/mesos
      - MESOS_DOCKER_STOP_TIMEOUT=50secs
      - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=15mins
      - MESOS_EXECUTOR_SHUTDOWN_GRACE_PERIOD=60secs
      - MESOS_RESOURCES=cpus:2;mem:2048;disk:20480;ports(*):[12000-12999]
      - MESOS_SYSTEMD_ENABLE_SUPPORT=false
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/tmp/hadoop-2.8.0:/hadoop"

  marathon:
    image: mesosphere/marathon:v1.6.549
    hostname: marathon
    ports:
     - "8080:8080"
    depends_on:
      - zookeeper
      - mesos-master
      - mesos-slave
    extra_hosts:
      - "seaof-172-17-0-1.arukascloud.io:172.17.0.1"
    environment:
      - MARATHON_ENV_VARS_PREFIX="MARATHON_"
      - MARATHON_ZK=zk://zookeeper:2181/marathon
      - MARATHON_MASTER=zk://zookeeper:2181/mesos

  zookeeper:
    image: zookeeper:3.4.13
    hostname: zookeeper
    ports:
      - "2181:2181"
